<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-SSDS6GEK" failures="2" tests="8" name="Retry" time="0.188" errors="0" timestamp="2023-08-04T17:22:19 EDT">
  <testcase classname="Retry.Practice" name="demo1" time="0.031">
    <skipped/>
  </testcase> <!-- demo1 -->
  <testcase classname="Retry.Practice" name="demo1" time="0.004">
    <skipped/>
  </testcase> <!-- demo1 -->
  <testcase classname="Retry.Practice" name="demo1" time="0.002">
    <skipped/>
  </testcase> <!-- demo1 -->
  <testcase classname="Retry.Practice" name="demo1" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Retry.Practice.demo1(Practice.java:9)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- demo1 -->
  <testcase classname="Retry.Practice" name="demo2" time="0.001">
    <skipped/>
  </testcase> <!-- demo2 -->
  <testcase classname="Retry.Practice" name="demo2" time="0.001">
    <skipped/>
  </testcase> <!-- demo2 -->
  <testcase classname="Retry.Practice" name="demo2" time="0.004">
    <skipped/>
  </testcase> <!-- demo2 -->
  <testcase classname="Retry.Practice" name="demo2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at Retry.Practice.demo2(Practice.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- demo2 -->
</testsuite> <!-- Retry -->
